"""Build, check, pack, publish and fetch the accuracy suite's full corpus.

    python tools/accuracy/corpus.py build --out DIR [--member NAME ...]
    python tools/accuracy/corpus.py pins --member NAME [--member NAME ...]
    python tools/accuracy/corpus.py slices --from DIR
    python tools/accuracy/corpus.py digest
    python tools/accuracy/corpus.py pack DIR --out PATH
    python tools/accuracy/corpus.py publish TARBALL [--repo OWNER/NAME] [--dry-run]
    python tools/accuracy/corpus.py fetch [--dest DIR] [--repo OWNER/NAME]

tests/accuracy/corpus_goldens/corpus.toml pins every member: its repository,
the commit, the subset paths and the git object id each path must have at that
commit, the license file, the languages its scope declares, the
GIT_TEST_DATE_NOW epoch a run of it freezes git's clock at, and the files the
small corpus takes from it as a slice.

`build` fetches each member with a partial shallow clone (`--filter=blob:none
--depth 1`), checks out only its subset paths, and refuses a path whose object
id differs from its pin. It writes DIR/<member>/ holding the subset, the
license and a generated crapkit.toml; kit.corpus_run commits that directory
to a fresh repo with fixed dates when a test measures it. A member with
`history_since` also gets DIR/history/<member>.bundle: the real history from
that date, replayed with `git fast-export` into a fresh repo, because a bundle
of a shallow repo cannot be cloned.

`pins` prints the object ids to write into corpus.toml when a pin moves.
`slices` copies each member's slice files and license into the small corpus
under vendor/<member>/. `digest` names the corpus: the first 12 hex of a
sha256 over the member tables, so the small corpus can change without a new
full corpus. `pack` writes a tarball with sorted entries and zero mtimes, so
one tree packs to one byte string. `publish` uploads it as the prerelease
asset `corpus-<digest>` on the crapkit repository, once per digest: when that
release exists it prints so and exits 0. `fetch` downloads and unpacks it.

Exit codes: 0 done, 1 a pin or tree check failed, 3 a fetch or a tool failed.
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import io
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tarfile
import tempfile
import tomllib

REPO = Path(__file__).resolve().parents[2]
CORPUS_TOML = REPO / "tests" / "accuracy" / "corpus_goldens" / "corpus.toml"
SMALL = REPO / "tests" / "accuracy" / "corpus_goldens" / "small"
GITHUB_REPO = "JeanFrancoisGagne/crapkit"
EXIT_PIN, EXIT_INFRA = 1, 3
FIXED_DATE = "@1750000000 +0000"
SCOPE_TEMPLATE = """\
# Generated by tools/accuracy/corpus.py from corpus.toml: member {name}, {url} at {tag}.
[crapkit]
target = 6

[[scope]]
name = "{name}"
paths = {paths}
languages = {languages}
coverage_optional = true

[exclude]
globs = ["**/test/**", "**/tests/**", "**/testdata/**", "**/__tests__/**"]
"""


class CorpusError(RuntimeError):
    """A pin that does not hold, or a member table that says too little."""

    code = EXIT_PIN


class ToolFailed(CorpusError):
    """git or gh failed: a network or tool problem, not a pin that moved."""

    code = EXIT_INFRA


# --- the member table -------------------------------------------------------------

def load(path: Path = CORPUS_TOML) -> dict:
    return tomllib.loads(path.read_text(encoding="utf-8"))


def members(table: dict, wanted: list[str] | None = None) -> dict[str, dict]:
    """The member tables by name, all of them or the ones asked for."""
    found = table.get("member", {})
    unknown = sorted(set(wanted or ()) - set(found))
    if unknown:
        raise CorpusError(f"corpus.toml names no member {unknown[0]}")
    return {name: found[name] for name in (wanted or sorted(found))}


def digest(table: dict) -> str:
    """The full corpus's name: a sha256 over the member tables alone."""
    text = json.dumps(table.get("member", {}), sort_keys=True, ensure_ascii=True)
    return hashlib.sha256(text.encode("ascii")).hexdigest()[:12]


# --- git --------------------------------------------------------------------------

def git(cwd: Path, *args: str) -> str:
    done = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True,
                          encoding="utf-8", errors="replace")
    if done.returncode != 0:
        raise ToolFailed(f"git {' '.join(args)} exited {done.returncode} in {cwd}: "
                         f"{done.stderr.strip()}")
    return done.stdout


def _fetch(work: Path, member: dict) -> None:
    work.mkdir(parents=True)
    git(work, "init", "-q")
    git(work, "remote", "add", "origin", member["url"])
    git(work, "fetch", "-q", "--filter=blob:none", "--depth", "1", "origin", member["commit"])


def object_id(work: Path, commit: str, path: str) -> str:
    return git(work, "rev-parse", f"{commit}:{path}").strip()


def object_kind(work: Path, commit: str, path: str) -> str:
    return git(work, "cat-file", "-t", f"{commit}:{path}").strip()


def _pattern(work: Path, commit: str, path: str) -> str:
    """A non-cone sparse pattern: a tree keeps everything below it."""
    tail = "/" if object_kind(work, commit, path) == "tree" else ""
    return f"/{path}{tail}"


def check_pins(work: Path, name: str, member: dict) -> None:
    """Every subset path's object id at the pinned commit equals its pin."""
    paths, pins = member["paths"], member.get("trees", [])
    if len(pins) != len(paths):
        raise CorpusError(f"{name}: corpus.toml pins {len(pins)} object ids for "
                          f"{len(paths)} paths; run `corpus.py pins --member {name}`")
    for path, pinned in zip(paths, pins):
        found = object_id(work, member["commit"], path)
        if found != pinned:
            raise CorpusError(f"{name}: {path} at {member['commit'][:12]} is {found}, "
                              f"corpus.toml pins {pinned}")


def _checkout(work: Path, member: dict) -> None:
    wanted = [*member["paths"], member["license"]]
    patterns = [_pattern(work, member["commit"], path) for path in wanted]
    git(work, "sparse-checkout", "set", "--no-cone", *patterns)
    git(work, "checkout", "-q", member["commit"])


# --- writing a member ---------------------------------------------------------------

def scope_toml(name: str, member: dict) -> str:
    return SCOPE_TEMPLATE.format(name=name, url=member["url"], tag=member["tag"],
                                 paths=json.dumps(member["paths"]),
                                 languages=json.dumps(member["languages"]))


def _copy_path(work: Path, dest: Path, path: str) -> None:
    source, target = work / path, dest / path
    target.parent.mkdir(parents=True, exist_ok=True)
    if source.is_dir():
        shutil.copytree(source, target, dirs_exist_ok=True)
    else:
        shutil.copyfile(source, target)


def write_member(work: Path, dest: Path, name: str, member: dict) -> None:
    for path in [*member["paths"], member["license"]]:
        _copy_path(work, dest, path)
    (dest / "crapkit.toml").write_bytes(scope_toml(name, member).encode("utf-8"))


def build_member(scratch: Path, out: Path, name: str, member: dict) -> None:
    work = scratch / name
    _fetch(work, member)
    check_pins(work, name, member)
    _checkout(work, member)
    write_member(work, out / name, name, member)
    if member.get("history_since"):
        history_bundle(scratch / f"{name}-history", out / "history" / f"{name}.bundle", member)
    print(f"built {name} ({member['tag']})")


def history_bundle(work: Path, bundle: Path, member: dict) -> None:
    """The member's history since `history_since`, replayed into a fresh repo so
    the bundle has a root instead of a shallow boundary."""
    work.mkdir(parents=True)
    git(work, "init", "-q")
    git(work, "remote", "add", "origin", member["url"])
    git(work, "fetch", "-q", f"--shallow-since={member['history_since']}", "origin",
        member["commit"])
    git(work, "branch", "-f", "main", member["commit"])
    exported = subprocess.run(["git", "fast-export", "--reencode=yes", "main"], cwd=work,
                              capture_output=True, check=True).stdout
    fresh = work / "fresh"
    fresh.mkdir()
    git(fresh, "init", "-q")
    subprocess.run(["git", "fast-import", "--quiet"], cwd=fresh, input=exported, check=True)
    bundle.parent.mkdir(parents=True, exist_ok=True)
    git(fresh, "checkout", "-q", "main")
    git(fresh, "bundle", "create", str(bundle), "HEAD", "main")


def build(out: Path, table: dict, wanted: list[str] | None = None) -> list[str]:
    chosen = members(table, wanted)
    out.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="crapkit-corpus-",
                                     ignore_cleanup_errors=True) as scratch:
        for name, member in chosen.items():
            build_member(Path(scratch), out, name, member)
    (out / "DIGEST").write_text(digest(table) + "\n", encoding="utf-8")
    return list(chosen)


def pin_line(work: Path, name: str, member: dict) -> str:
    """The `trees` and `git_test_date_now` a member's table should hold: the
    object ids at its commit, and one day past the commit's committer time."""
    ids = [object_id(work, member["commit"], path) for path in member["paths"]]
    stamp = int(git(work, "log", "-1", "--format=%ct", member["commit"]).strip()) + 86_400
    return f"[member.{name}] trees = {json.dumps(ids)} git_test_date_now = {stamp}"


def pins(table: dict, wanted: list[str]) -> list[str]:
    lines = []
    with tempfile.TemporaryDirectory(prefix="crapkit-corpus-pins-",
                                     ignore_cleanup_errors=True) as scratch:
        for name, member in members(table, wanted).items():
            work = Path(scratch) / name
            _fetch(work, member)
            lines.append(pin_line(work, name, member))
    return lines


# --- slices into the small corpus ---------------------------------------------------------

def slice_files(name: str, member: dict) -> list[tuple[str, str]]:
    """(path in the built member, path under the small corpus) for each slice file."""
    pairs = [(path, f"vendor/{name}/{Path(path).name}") for path in member.get("slice", [])]
    if pairs:
        pairs.append((member["license"], f"vendor/{name}/{Path(member['license']).name}"))
    return pairs


def copy_slices(built: Path, small: Path, table: dict) -> list[str]:
    written = []
    for name, member in members(table).items():
        for source, target in slice_files(name, member):
            (small / target).parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(built / name / source, small / target)
            written.append(target)
    return written


# --- pack, publish, fetch -------------------------------------------------------------

def _entries(root: Path) -> list[Path]:
    return sorted(path for path in root.rglob("*") if path.is_file())


def _info(root: Path, path: Path) -> tarfile.TarInfo:
    info = tarfile.TarInfo(path.relative_to(root).as_posix())
    info.size, info.mtime, info.mode = path.stat().st_size, 0, 0o644
    info.uid = info.gid = 0
    info.uname = info.gname = ""
    return info


def pack(root: Path, out: Path) -> str:
    """A reproducible tar.gz of root; returns its sha256."""
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode="w", format=tarfile.PAX_FORMAT) as archive:
        for path in _entries(root):
            with path.open("rb") as handle:
                archive.addfile(_info(root, path), handle)
    with out.open("wb") as raw, gzip.GzipFile(fileobj=raw, mode="wb", mtime=0,
                                             filename="") as zipped:
        zipped.write(buffer.getvalue())
    return hashlib.sha256(out.read_bytes()).hexdigest()


def tag(table: dict) -> str:
    return f"corpus-{digest(table)}"


def gh(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["gh", *args], capture_output=True, text=True, encoding="utf-8",
                          errors="replace")


def _published(name: str, repo: str) -> bool:
    return gh("release", "view", name, "--repo", repo).returncode == 0


def publish_argv(name: str, tarball: Path, repo: str) -> list[str]:
    """The one gh call that publishes: a prerelease, never marked latest."""
    return ["release", "create", name, str(tarball), "--repo", repo, "--prerelease",
            "--latest=false", "--title", f"accuracy corpus {name}",
            "--notes", "The accuracy suite's full corpus; see tools/accuracy/corpus.py."]


def publish(tarball: Path, table: dict, repo: str, dry_run: bool) -> str:
    name = tag(table)
    if _published(name, repo):
        return f"{name} is already published on {repo}; nothing to do"
    argv = publish_argv(name, tarball, repo)
    if dry_run:
        return "would run: gh " + " ".join(argv)
    done = gh(*argv)
    if done.returncode != 0:
        raise ToolFailed(f"gh release create {name} exited {done.returncode}: {done.stderr.strip()}")
    return f"published {name} on {repo}"


def default_dest() -> Path:
    base = os.environ.get("LOCALAPPDATA") or os.path.expanduser("~/.cache")
    return Path(base) / "crapkit-accuracy" / "corpus"


def fetch(dest: Path, table: dict, repo: str) -> Path:
    """The unpacked corpus for this digest, downloaded once."""
    name = tag(table)
    target = dest / name
    if (target / "DIGEST").is_file():
        return target
    target.mkdir(parents=True, exist_ok=True)
    done = gh("release", "download", name, "--repo", repo, "--dir", str(target), "--clobber")
    if done.returncode != 0:
        raise ToolFailed(f"gh release download {name} exited {done.returncode}: "
                         f"{done.stderr.strip()}")
    for tarball in target.glob("*.tar.gz"):
        with tarfile.open(tarball) as archive:
            archive.extractall(target, filter="data")
    return target


# --- commands ---------------------------------------------------------------------------

def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="corpus.py", description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    build_cmd = sub.add_parser("build")
    build_cmd.add_argument("--out", type=Path, required=True)
    build_cmd.add_argument("--member", action="append")
    pins_cmd = sub.add_parser("pins")
    pins_cmd.add_argument("--member", action="append", required=True)
    slices_cmd = sub.add_parser("slices")
    slices_cmd.add_argument("--from", dest="built", type=Path, required=True)
    sub.add_parser("digest")
    pack_cmd = sub.add_parser("pack")
    pack_cmd.add_argument("root", type=Path)
    pack_cmd.add_argument("--out", type=Path, required=True)
    publish_cmd = sub.add_parser("publish")
    publish_cmd.add_argument("tarball", type=Path)
    publish_cmd.add_argument("--repo", default=GITHUB_REPO)
    publish_cmd.add_argument("--dry-run", action="store_true")
    fetch_cmd = sub.add_parser("fetch")
    fetch_cmd.add_argument("--dest", type=Path, default=None)
    fetch_cmd.add_argument("--repo", default=GITHUB_REPO)
    return parser


def _run(args, table: dict) -> list[str]:
    commands = {
        "build": lambda: [f"built {len(build(args.out, table, args.member))} member(s) "
                          f"into {args.out}"],
        "pins": lambda: pins(table, args.member),
        "slices": lambda: copy_slices(args.built, SMALL, table),
        "digest": lambda: [digest(table)],
        "pack": lambda: [f"{args.out} sha256 {pack(args.root, args.out)}"],
        "publish": lambda: [publish(args.tarball, table, args.repo, args.dry_run)],
        "fetch": lambda: [str(fetch(args.dest or default_dest(), table, args.repo))],
    }
    return commands[args.command]()


def main(argv: list[str] | None = None, table_path: Path = CORPUS_TOML) -> int:
    args = _parser().parse_args(argv)
    try:
        lines = _run(args, load(table_path))
    except CorpusError as failed:
        print(f"corpus.py: {failed}", file=sys.stderr)
        return failed.code
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
