"""The CLI, split by command family. This module is the seam every other file
still imports through: `crapkit.cli:main` is the console script and `python -m
crapkit`, and the test suite reaches dozens of the helpers below by name. Every
top-level name the single-file cli.py exposed is re-exported here, so nothing
outside the package has to know which family a helper landed in. No logic lives
here: each name is defined in the module its family owns.

The re-export is by name, not by import. Eight `from .family import ...` lines
loaded all eight families before anything read one of their names, which put the
cost of every subcommand on every invocation. `_OWNER` says which module owns
each name and `__getattr__` fetches it the first time it is read.
"""

from __future__ import annotations

_OWNER = {
    "SCHEMA_VERSION": "_shared",
    "_AMBIGUOUS_TEST": "verifying",
    "_BriefLoader": "queue",
    "_Corpus": "scoring",
    "_Handles": "queue",
    "_CLAUDE_SUBCOMMANDS": "parser",
    "_SCRIPT_SUFFIXES": "admin",
    "_ScoredRun": "scoring",
    "_VersionAction": "parser",
    "_advise": "claude_hook",
    "_advisory_lines": "claude_hook",
    "_actionable": "queue",
    "_analysis_tools": "_shared",
    "_analysis_workers": "scoring",
    "_answerable": "claude_hook",
    "_analyzed_corpus": "scoring",
    "_apply_verify_override": "verifying",
    "_at_default_thresholds": "analyses",
    "_at_level": "admin",
    "_baseline_behind": "verifying",
    "_baseline_failures": "verifying",
    "_baseline_rows": "scoring",
    "_batch_json": "queue",
    "_batch_rows": "queue",
    "_brief_batch": "queue",
    "_brief_churn": "queue",
    "_brief_coupling": "queue",
    "_brief_lines_text": "queue",
    "_brief_mark": "queue",
    "_brief_packet": "queue",
    "_brief_payload": "queue",
    "_brief_target": "queue",
    "_brief_twins": "queue",
    "_brief_versions": "queue",
    "_build_inventory": "scoring",
    "_breaches": "claude_hook",
    "_by_scope": "scoring",
    "_ceiling_breaches": "scoring",
    "_changed": "claude_hook",
    "_churn_text": "queue",
    "_claim_matches": "queue",
    "_claimable": "queue",
    "_claims_summary": "queue",
    "_claims_to_release": "queue",
    "_collect_lanes": "scoring",
    "_collect_mutants": "analyses",
    "_config": "claude_hook",
    "_contexts_for_span": "reports",
    "_coupling_pairs": "analyses",
    "_coverage_summary": "scoring",
    "_covered_scope_names": "admin",
    "_diff_cover_breach": "verifying",
    "_diff_proc": "claude_hook",
    "_digest_pair": "reports",
    "_dirty_tag": "_shared",
    "_doctor_findings": "admin",
    "_doctor_hook_modes": "admin",
    "_doctor_keys": "admin",
    "_doctor_lane_summary": "admin",
    "_doctor_lanes": "admin",
    "_doctor_oversized": "admin",
    "_doctor_plugin": "admin",
    "_doctor_report": "admin",
    "_doctor_results_artifacts": "admin",
    "_doctor_scope_files": "admin",
    "_doctor_scopes": "admin",
    "_doctor_tools": "admin",
    "_doctor_tune": "admin",
    "_doctor_unclaimed": "admin",
    "_doctor_uncovered": "admin",
    "_doctor_unmeasured": "admin",
    "_edited_file": "claude_hook",
    "_edited_path": "claude_hook",
    "_emit_baseline": "verifying",
    "_emit_coverage_findings": "scoring",
    "_emit_doctor": "admin",
    "_emit_findings": "_shared",
    "_emit_next": "queue",
    "_emit_verify_findings": "verifying",
    "_empty_reasons": "queue",
    "_entry_json": "queue",
    "_excluded_item": "queue",
    "_execute_lanes": "scoring",
    "_execute_parallel": "scoring",
    "_explain_commits": "reports",
    "_explain_extras": "reports",
    "_explain_tests": "reports",
    "_export_scored": "scoring",
    "_extend_gitignore": "admin",
    "_fewer_tests_line": "verifying",
    "_file_sizer": "_shared",
    "_flag_counts": "scoring",
    "_flake_retry": "verifying",
    "_gate_candidates": "scoring",
    "_gate_line": "_shared",
    "_gated_violations": "verifying",
    "_grant_env_override": "verifying",
    "_group_files_by_scope": "verifying",
    "_guard_ratchet_stamp": "verifying",
    "_handle": "queue",
    "_held_marks": "verifying",
    "_hook_handlers": "admin",
    "_hook_modes": "admin",
    "_hook_protocols": "admin",
    "_interpreter": "admin",
    "_is_test_path": "verifying",
    "_judge": "claude_hook",
    "_junit_seconds": "admin",
    "_lane_command_problems": "admin",
    "_lane_durations": "admin",
    "_lane_problem": "admin",
    "_lane_problems": "admin",
    "_lane_report": "admin",
    "_lane_reports": "admin",
    "_lane_reuse": "scoring",
    "_lane_seconds": "admin",
    "_latest_full_run": "ratchet_cmds",
    "_latest_scored": "_shared",
    "_latest_span": "reports",
    "_listed_files": "admin",
    "_lizard_version": "admin",
    "_load_ratchet_or_die": "_shared",
    "_load_repo_config": "_shared",
    "_load_sources": "_shared",
    "_manifest_version": "admin",
    "_mark_text": "queue",
    "_matching_rows": "queue",
    "_maybe_claim": "queue",
    "_marks_for": "claude_hook",
    "_maybe_flake_retry": "verifying",
    "_merge_stamp": "ratchet_cmds",
    "_missing_named_script": "admin",
    "_more_skips_line": "verifying",
    "_mutation_targets": "analyses",
    "_name_matches": "queue",
    "_name_prefix": "queue",
    "_named_baseline": "verifying",
    "_named_claims": "queue",
    "_named_protocol": "admin",
    "_newest_coverage_run": "admin",
    "_newest_run_report": "admin",
    "_next_head": "queue",
    "_next_item_payload": "queue",
    "_next_ranked": "queue",
    "_next_reasons": "queue",
    "_next_step": "admin",
    "_no_baseline": "verifying",
    "_no_handle_message": "queue",
    "_no_lane_debt": "queue",
    "_no_lane_gap": "queue",
    "_no_line_message": "queue",
    "_no_match_message": "queue",
    "_no_scopes_reason": "admin",
    "_no_tighten_line": "verifying",
    "_no_twin_message": "queue",
    "_note_marked_staged": "verifying",
    "_note_stale_staged": "verifying",
    "_open_store": "_shared",
    "_owning_scope": "verifying",
    "_package_json": "admin",
    "_packet_commands": "queue",
    "_packet_context": "queue",
    "_packet_gate": "queue",
    "_packet_scope": "queue",
    "_payload": "claude_hook",
    "_pick_baseline": "verifying",
    "_pick_function": "queue",
    "_plugin_json": "admin",
    "_policy_findings": "ratchet_cmds",
    "_present_markers": "admin",
    "_present_on_disk": "scoring",
    "_prior_crap": "verifying",
    "_print_batches": "queue",
    "_print_brief": "queue",
    "_print_brief_context": "queue",
    "_print_brief_neighbours": "queue",
    "_print_claims": "queue",
    "_print_coverage": "scoring",
    "_print_duplication": "analyses",
    "_print_finding_split": "verifying",
    "_print_findings": "admin",
    "_print_history": "reports",
    "_print_init_summary": "admin",
    "_print_json": "_shared",
    "_print_mutation": "analyses",
    "_print_prune": "reports",
    "_print_ratchet_report": "ratchet_cmds",
    "_print_released": "queue",
    "_print_rescore_table": "scoring",
    "_print_trend": "reports",
    "_print_uncovered": "reports",
    "_print_verify_findings": "verifying",
    "_progress": "scoring",
    "_prune_renames": "ratchet_cmds",
    "_pruned": "ratchet_cmds",
    "_pushdown_floor": "queue",
    "_pytest_cov_probe": "admin",
    "_range_lines": "analyses",
    "_rankable": "queue",
    "_ratchet_entries": "_shared",
    "_ratchet_mark": "reports",
    "_ratchet_merge": "ratchet_cmds",
    "_ratchet_move": "ratchet_cmds",
    "_ratchet_report": "ratchet_cmds",
    "_ratchet_sha256": "verifying",
    "_reconfigure_streams": "parser",
    "_records": "claude_hook",
    "_records_by_scope": "scoring",
    "_refuse_empty_lane_run": "scoring",
    "_refuse_lane_less_verify": "verifying",
    "_release_claims": "verifying",
    "_release_target": "queue",
    "_report": "claude_hook",
    "_report_lanes": "reports",
    "_report_payload": "reports",
    "_report_verify": "verifying",
    "_report_worklist": "reports",
    "_require_ancestor": "verifying",
    "_rescore_analyze": "scoring",
    "_rescore_gate": "scoring",
    "_rescore_json": "scoring",
    "_rescore_overlay": "scoring",
    "_rescored_records": "scoring",
    "_resolve_batch": "queue",
    "_resolve_batches": "queue",
    "_resolve_top": "queue",
    "_route_unowned": "verifying",
    "_row_at_line": "queue",
    "_row_by_handle": "queue",
    "_row_ceiling": "queue",
    "_row_marker": "queue",
    "_run_kind": "scoring",
    "_run_lanes": "scoring",
    "_run_line": "reports",
    "_run_one_lane": "scoring",
    "_runs_list": "reports",
    "_runs_prune": "reports",
    "_scope_config": "queue",
    "_scope_rollup_from_agg": "reports",
    "_scoped": "claude_hook",
    "_scoped_command": "verifying",
    "_scored_run": "scoring",
    "_scored_store": "queue",
    "_select_lanes": "scoring",
    "_send_digest_alert": "reports",
    "_sequencing": "claude_hook",
    "_settle_verify": "verifying",
    "_skip_reason": "queue",
    "_split_marked": "verifying",
    "_split_worklist": "queue",
    "_stale_warning": "queue",
    "_store_if_any": "admin",
    "_store_path": "admin",
    "_store_report": "admin",
    "_suite_size_lines": "verifying",
    "_taint_note": "verifying",
    "_traced_lane": "scoring",
    "_tracked": "claude_hook",
    "_tracked_files": "scoring",
    "_trend_payload": "reports",
    "_trend_row": "reports",
    "_tsv_baseline": "verifying",
    "_unclaimed": "queue",
    "_uncovered_fields": "queue",
    "_uncovered_scopes": "admin",
    "_uncovered_text": "reports",
    "_under_scope_path": "verifying",
    "_unknown_key_text": "admin",
    "_unmarked_breaches": "scoring",
    "_unknown_claude_command": "parser",
    "_untracked_of": "scoring",
    "_untrusted_reason": "verifying",
    "_verdict": "claude_hook",
    "_verify_attribution": "verifying",
    "_verify_baseline": "verifying",
    "_verify_basis": "verifying",
    "_verify_exit_code": "verifying",
    "_verify_result": "verifying",
    "_verify_store": "verifying",
    "_version_line": "parser",
    "_version_report": "admin",
    "_warn_diff_uncovered": "verifying",
    "_warn_missing_pytest_cov": "admin",
    "_warn_suite_shrink": "verifying",
    "_warn_untracked": "scoring",
    "_watch_banner": "admin",
    "_watch_cycle": "admin",
    "_watch_cycles": "admin",
    "_watch_rescore": "admin",
    "_watched_files": "admin",
    "_working_marks": "ratchet_cmds",
    "_worklist_batches": "queue",
    "_worklist_marks": "queue",
    "_worklist_payload": "queue",
    "_worklist_print": "queue",
    "_write_report": "reports",
    "_write_tsv": "_shared",
    "_wrong_baseline": "verifying",
    "build_parser": "parser",
    "cmd_brief": "queue",
    "cmd_claims": "queue",
    "cmd_claude_hook": "claude_hook",
    "cmd_coupling": "analyses",
    "cmd_coverage": "scoring",
    "cmd_digest": "reports",
    "cmd_doctor": "admin",
    "cmd_duplication": "analyses",
    "cmd_explain": "reports",
    "cmd_hook_precommit": "verifying",
    "cmd_init": "admin",
    "cmd_inventory": "scoring",
    "cmd_mcp": "analyses",
    "cmd_mutate": "analyses",
    "cmd_next_item": "queue",
    "cmd_overrides": "reports",
    "cmd_ratchet": "ratchet_cmds",
    "cmd_report": "reports",
    "cmd_rescore": "scoring",
    "cmd_runs": "reports",
    "cmd_test_scoped": "verifying",
    "cmd_trend": "reports",
    "cmd_verify": "verifying",
    "cmd_watch": "admin",
    "cmd_worklist": "queue",
    "main": "parser",
}

_MODULES = frozenset(_OWNER.values())

__all__ = sorted(_OWNER)


def __getattr__(name):
    """Re-export on demand: reading a name loads the one family that defines it."""
    family = _OWNER.get(name)
    if family is None:
        return _submodule(name)
    from importlib import import_module

    value = getattr(import_module(f"{__name__}.{family}"), name)
    globals()[name] = value
    return value


def _submodule(name: str):
    """`crapkit.cli.admin` after a bare `import crapkit.cli`: the family modules
    were attributes here because __init__ imported every one of them."""
    if name not in _MODULES:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    from importlib import import_module

    return import_module(f"{__name__}.{name}")


def __dir__():
    return sorted(set(_OWNER) | _MODULES | set(globals()))
