"""doctor names a commit gate that is set up and never judges anything.

Two setups passed every commit without a word:

- Route 1 writes crapkit's hook to .git/hooks/pre-commit. A core.hooksPath set
  anywhere else (a global one, husky's .husky/_) sends git to another
  directory, and git runs no hook from .git/hooks at all.
- Route 3 names crapkit-gate in .pre-commit-config.yaml, and nothing ran
  `pre-commit install`.

WARN, never FAIL: the commit still succeeds; it just was not gated. CI's
`pre-commit run --all-files` is no such setup: outside a commit, with nothing
staged, the hook judges every tracked file, so doctor says nothing about it.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from crapkit.cli import admin
from crapkit.doctor import GateHook, HookRoute, skipped_gates

ROUTE_1 = "#!/bin/sh\nexec python -m crapkit hook-precommit\n"
GATE_CONFIG = ("repos:\n  - repo: https://github.com/JeanFrancoisGagne/crapkit\n    rev: v0.8.0\n"
               "    hooks:\n      - id: crapkit-gate\n")
# The file `pre-commit install` writes, cut to the line that runs the framework.
FRAMEWORK_HOOK = ("#!/usr/bin/env bash\n# File generated by pre-commit\n"
                  "exec pre-commit hook-impl --hook-type=pre-commit\n")
LOCAL_HOOK = GateHook("/r/.git/hooks/pre-commit", ROUTE_1,
                      "git config --local core.hooksPath /r/.git/hooks")
COMMITTED_HOOK = GateHook("githooks/pre-commit", ROUTE_1, "git config core.hooksPath githooks")


def route(**changes) -> HookRoute:
    base = dict(effective="/home/u/.githooks/pre-commit", effective_text="",
                edit="/home/u/.githooks/pre-commit", scope="global", value="/home/u/.githooks")
    return HookRoute(**{**base, **changes})


UNSET = dict(effective=".git/hooks/pre-commit", edit=".git/hooks/pre-commit", scope="", value="")


# --- the hook git is sent away from ---------------------------------------------

def test_a_crapkit_hook_git_never_runs_is_one_warn_naming_both_paths_and_both_fixes():
    (finding,) = skipped_gates(route(), (LOCAL_HOOK,), framework=False)

    assert finding.level == "WARN"
    assert finding.text == (
        "/r/.git/hooks/pre-commit runs crapkit's gate, but core.hooksPath (global config: "
        "/home/u/.githooks) sends git to /home/u/.githooks/pre-commit, so every commit here "
        "skips the gate without a word; run `git config --local core.hooksPath "
        "/r/.git/hooks` in this repo, or call crapkit hook-precommit from "
        "/home/u/.githooks/pre-commit")


def test_a_committed_hook_a_clone_never_pointed_git_at_names_route_2_s_config_line():
    """Route 2 commits githooks/pre-commit and asks every clone to run one git
    config line. A clone that skipped it commits breaches with no gate."""
    (finding,) = skipped_gates(route(**UNSET), (COMMITTED_HOOK,), framework=False)

    assert finding.text == (
        "githooks/pre-commit runs crapkit's gate, but core.hooksPath is unset and git runs "
        ".git/hooks/pre-commit, so every commit here skips the gate without a word; run "
        "`git config core.hooksPath githooks` in this repo, or call crapkit hook-precommit "
        "from .git/hooks/pre-commit")


def test_husky_taking_the_hooks_path_back_names_the_file_a_user_edits():
    """husky 9 sets core.hooksPath to .husky/_ on every npm install, and its
    stub there runs .husky/pre-commit, which is where a gate line goes."""
    husky = route(effective=".husky/_/pre-commit", effective_text='. "$(dirname "$0")/h"\nnpm test\n',
                  edit=".husky/pre-commit", scope="local", value=".husky/_")

    (finding,) = skipped_gates(husky, (COMMITTED_HOOK,), framework=False)

    assert "core.hooksPath (local config: .husky/_) sends git to .husky/_/pre-commit" in finding.text
    assert finding.text.endswith("or call crapkit hook-precommit from .husky/pre-commit")


@pytest.mark.parametrize("changes, hooks", [
    ({**UNSET, "effective_text": ROUTE_1}, (LOCAL_HOOK,)),
    ({"effective_text": "#!/bin/sh\nnpx lint-staged\ncrapkit hook-precommit\n"}, (LOCAL_HOOK,)),
    ({}, ()),
    ({}, (LOCAL_HOOK._replace(text=""),)),
    ({}, (LOCAL_HOOK._replace(text="#!/bin/sh\nnpx lint-staged\n"),)),
], ids=["git-runs-it", "hooks-path-calls-crapkit", "no-gate-hook", "empty-hook", "hook-not-crapkit"])
def test_a_hook_git_does_run_or_one_that_is_not_crapkit_says_nothing(changes, hooks):
    assert skipped_gates(route(**changes), hooks, framework=False) == ()


def test_two_skipped_gate_hooks_are_one_warn_each():
    found = skipped_gates(route(), (LOCAL_HOOK, COMMITTED_HOOK), framework=False)

    assert [f.text.split()[0] for f in found] == ["/r/.git/hooks/pre-commit", "githooks/pre-commit"]


# --- Route 3 installed nowhere ------------------------------------------------------

def test_a_pre_commit_config_naming_the_gate_with_no_framework_hook_says_run_install():
    (finding,) = skipped_gates(route(**UNSET), (), framework=True)

    assert finding.text == (
        ".pre-commit-config.yaml names crapkit-gate, but core.hooksPath is unset and git runs "
        ".git/hooks/pre-commit, which pre-commit did not write, so every commit here skips the "
        "gate without a word; run `pre-commit install` in this repo")


def test_under_a_hooks_path_the_framework_line_names_the_file_to_call_crapkit_from():
    (finding,) = skipped_gates(route(), (), framework=True)

    assert finding.text.endswith(
        "`pre-commit install` refuses while core.hooksPath is set, so call crapkit "
        "hook-precommit from /home/u/.githooks/pre-commit")


@pytest.mark.parametrize("text", [FRAMEWORK_HOOK, "#!/bin/sh\nexec pre-commit run\n",
                                  "#!/bin/sh\nexec prek run\n"])
def test_a_framework_hook_git_runs_is_the_gate(text):
    assert skipped_gates(route(effective_text=text), (), framework=True) == ()


def test_the_framework_s_own_hook_shadowed_by_a_global_path_is_a_skipped_gate():
    installed = LOCAL_HOOK._replace(text=FRAMEWORK_HOOK)

    (finding,) = skipped_gates(route(), (installed,), framework=True)

    assert finding.text.startswith("/r/.git/hooks/pre-commit runs crapkit's gate, but core.hooksPath")


def test_a_framework_hook_without_the_gate_in_its_config_is_not_a_gate():
    installed = LOCAL_HOOK._replace(text=FRAMEWORK_HOOK)

    assert skipped_gates(route(), (installed,), framework=False) == ()


# --- pre-commit in CI -----------------------------------------------------------

# --- through git ------------------------------------------------------------------

def _git(root: Path, *args: str, env: dict | None = None) -> str:
    return subprocess.run(["git", *args], cwd=root, check=True, capture_output=True, text=True,
                          env=env).stdout.strip()


@pytest.fixture
def repo(tmp_path, monkeypatch):
    """A repo with Route 1 written, and a global git config this test owns."""
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("GIT_CONFIG_GLOBAL", str(home / ".gitconfig"))
    monkeypatch.setenv("GIT_CONFIG_NOSYSTEM", "1")
    root = tmp_path / "repo"
    root.mkdir()
    _git(root, "init", "-q")
    hook = root / ".git" / "hooks" / "pre-commit"
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(ROUTE_1, encoding="utf-8")
    return root


def test_route_1_under_a_global_hooks_path_warns_and_the_named_fix_clears_it(repo, tmp_path):
    global_hooks = tmp_path / "home" / ".githooks"
    global_hooks.mkdir()
    _git(repo, "config", "--global", "core.hooksPath", global_hooks.as_posix())

    (finding,) = admin._doctor_silent_gates(repo)
    assert "(global config: " in finding.text
    assert f"sends git to {(global_hooks / 'pre-commit').resolve().as_posix()}" in finding.text

    fix = finding.text.split("`")[1]
    _git(repo, *fix.split()[1:])
    assert admin._doctor_silent_gates(repo) == []
    assert Path(_git(repo, "rev-parse", "--path-format=absolute", "--git-path",
                     "hooks/pre-commit")).resolve() == (repo / ".git/hooks/pre-commit").resolve()


def test_route_1_with_no_hooks_path_says_nothing(repo):
    assert admin._doctor_silent_gates(repo) == []


def test_pre_commit_in_a_workflow_over_the_gate_says_nothing(repo):
    """The CI run judges every tracked file, so it is a gate, not a silent one."""
    (repo / ".pre-commit-config.yaml").write_text(GATE_CONFIG, encoding="utf-8")
    workflows = repo / ".github" / "workflows"
    workflows.mkdir(parents=True)
    (workflows / "lint.yaml").write_text("steps:\n  - run: pre-commit run --all-files\n",
                                         encoding="utf-8")

    assert admin._doctor_silent_gates(repo) == []


def test_outside_a_repository_nothing_is_read(tmp_path):
    assert admin._doctor_silent_gates(tmp_path) == []


def _isolated_git(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setenv("GIT_CONFIG_GLOBAL", str(tmp_path / ".gitconfig"))
    monkeypatch.setenv("GIT_CONFIG_NOSYSTEM", "1")


def test_a_clone_that_skipped_route_2_s_config_line_warns_and_the_named_fix_clears_it(tmp_path,
                                                                                     monkeypatch):
    _isolated_git(tmp_path, monkeypatch)
    root = tmp_path / "clone"
    (root / "githooks").mkdir(parents=True)
    _git(root, "init", "-q")
    (root / "githooks" / "pre-commit").write_text(ROUTE_1, encoding="utf-8")
    _git(root, "add", "githooks/pre-commit")

    (finding,) = admin._doctor_silent_gates(root)
    assert finding.text.startswith("githooks/pre-commit runs crapkit's gate, but core.hooksPath "
                                   "is unset and git runs .git/hooks/pre-commit")

    fix = finding.text.split("`")[1]
    assert fix == "git config core.hooksPath githooks"
    _git(root, *fix.split()[1:])
    assert admin._doctor_silent_gates(root) == []


def test_a_committed_gate_below_the_crapkit_root_s_repo_top_is_found_from_the_root(tmp_path,
                                                                                  monkeypatch):
    """A crapkit root below the git top still reads the hooks the top commits."""
    _isolated_git(tmp_path, monkeypatch)
    top = tmp_path / "mono"
    (top / "tools" / "githooks").mkdir(parents=True)
    (top / "packages" / "api").mkdir(parents=True)
    _git(top, "init", "-q")
    (top / "tools" / "githooks" / "pre-commit").write_text(ROUTE_1, encoding="utf-8")
    _git(top, "add", "tools/githooks/pre-commit")

    (finding,) = admin._doctor_silent_gates(top / "packages" / "api")
    assert "`git config core.hooksPath tools/githooks`" in finding.text


def test_husky_s_hooks_path_over_a_committed_gate_names_husky_s_own_file(tmp_path, monkeypatch):
    _isolated_git(tmp_path, monkeypatch)
    root = tmp_path / "repo"
    (root / "githooks").mkdir(parents=True)
    (root / ".husky" / "_").mkdir(parents=True)
    _git(root, "init", "-q")
    (root / "githooks" / "pre-commit").write_text(ROUTE_1, encoding="utf-8")
    (root / ".husky" / "pre-commit").write_text("npm test\n", encoding="utf-8")
    (root / ".husky" / "_" / "pre-commit").write_text('. "$(dirname "$0")/h"\n', encoding="utf-8")
    _git(root, "add", "githooks/pre-commit", ".husky/pre-commit")
    _git(root, "config", "core.hooksPath", ".husky/_")

    (finding,) = admin._doctor_silent_gates(root)
    assert "core.hooksPath (local config: .husky/_) sends git to .husky/_/pre-commit" in finding.text
    assert finding.text.endswith("or call crapkit hook-precommit from .husky/pre-commit")

    (root / ".husky" / "pre-commit").write_text("npm test\npython -m crapkit hook-precommit\n",
                                                encoding="utf-8")
    assert admin._doctor_silent_gates(root) == []


def test_a_pre_commit_config_naming_the_gate_before_pre_commit_install_is_named(repo):
    (repo / ".git" / "hooks" / "pre-commit").unlink()
    (repo / ".pre-commit-config.yaml").write_text(GATE_CONFIG, encoding="utf-8")

    (finding,) = admin._doctor_silent_gates(repo)
    assert finding.text.endswith("run `pre-commit install` in this repo")

    (repo / ".git" / "hooks" / "pre-commit").write_text(FRAMEWORK_HOOK, encoding="utf-8")
    assert admin._doctor_silent_gates(repo) == []
